### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by migueldelmazo** [Adalab/modulo-2-evaluacion-intermedia-nataliamateo#1]
Really cool job @nataliamateo!!!

Here you have some tips to improve the exercise:

### JavaScript: basic

- [x] On page load, execute 'getRandomNumber' function and store the returned value on a constant to work with it later.
- [x] If you call 'getRandomNumer' function inside the event callback, you will be creating a new random number each time the user clicks the button. That makes the game really complex and the hints will not have sense. Let's generate the random number when the page loads instead.
- [x] Define the logic to make the counter work.
- [x] Remove console inside if.
- [x] Check if the number is less than 1 or greater than 100.
- [x] Remember that you can't reassign the value of a constant variable.
- [x] Remember that every time we use `.innerHTML` or `.value` to get DOM content we receive a string. Sometimes we will need to use something like `parseInt()` to convert it to a number.
- [x] Remove debugger and other unnecessary code

### JavaScript: advanced

- [ ] Move the feedback logic to a function and execute it on each click.
- [ ] Move you counter logic into a function and execute it on each click.
- [ ] You are writing many times "trackEl.innerHTML = 'something';", what about making a function that accepts a string as param and paints it into 'trackEl'?
- [ ] Use `ev.preventDefault()`.

### HTML

- [x] Remove action and method attributes
- [ ] Use placeholder.

### Steps to finish the game (for those far from the solution)

You are close to the exercise solution, but here you have a steps guide to complete it anyway ;)

1. Save a reference to DOM elements in variables.
2. Generate the random number and save it to a variable.
3. Init counter of trials to 0.
4. Define a function that executes when the user clicks on the button, that

- increments the counter and paints its value in the HTML.
- collect the value of the HTML input and compare it with the random number.
  - if they are equal, draw a 'You Win' message.
  - if it's lower, draw a 'Too short' message.
  - if it's higher, draw a 'Too long' message.

5. Assign a listener to the button click to execute the previous function.

### Further challenges

Then you can improve the game as you please, here you have some ideas:

- Add new feedback when the number is bigger than 100 or smaller than 0.
- Manage when the user hits the button and the input is empty.
- Make the input work when hitting enter key.
- Add a reset button that cleans the input, the counter, writes the initial feedback and generates a new random number to play again!
- Whatever you want!

### Call to action

Let me know if you have any doubts ;)

Go for it!!

> Do not close this issue until your teacher asks you to

**Comment by nataliamateo** [comment]
Hola @migueldelmazo ! Gracias por comentar mi ejercicio.

Lo he subido de nuevo con las correcciones, aunque no entiendo el punto de  Use placeholder en el HTML no se si se refiere a que el input tipo numérico necesita un placeholder.

Por otro lado no puedo tachar los cuadraditos ya que se ralla la página y no me deja seleccionarlos aun así he ido, o lo he intentado, seguirlos uno a uno.
Tampoco he realizado por ahora los Further Challenges ya que me he centrado en arreglar lo principal, si añado algo nuevo lo reflejaré.
